name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python from `pyproject.toml`
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup `task` runner
        uses: go-task/setup-task@v1

      - name: Setup `uv` CLI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run `uv sync` to install project (dev) dependencies
        run: uv sync

      - name: Run tests via Taskfile
        run: task test

  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python from `pyproject.toml`
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup `task` runner
        uses: go-task/setup-task@v1

      - name: Setup `uv` CLI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run `uv sync` to install project (dev) dependencies
        run: uv sync

      - name: Run lint via Taskfile
        run: task lint

  check-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python from `pyproject.toml`
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup `task` runner
        uses: go-task/setup-task@v1

      - name: Setup `uv` CLI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run `uv sync` to install project (dev) dependencies
        run: uv sync

      - name: Run format check via Taskfile
        run: task check-format

  build-package:
    name: Build package
    runs-on: ubuntu-latest
    needs: [test, lint, check-format]
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python from `pyproject.toml`
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Setup `task` runner
        uses: go-task/setup-task@v1

      - name: Setup `uv` CLI
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Run `uv sync` to install project (dev) dependencies
        run: uv sync

      - name: Build package via Taskfile
        run: task build
